//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApiWrapperDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMSApiWrapperDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktionen ähnelt.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die konnte nicht geändert werden. ähnelt.
        /// </summary>
        public static string ChangeASerieFromTheTitle {
            get {
                return ResourceManager.GetString("ChangeASerieFromTheTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufnahmen zur Serie ähnelt.
        /// </summary>
        public static string ChangesSeriesFromNumberToName {
            get {
                return ResourceManager.GetString("ChangesSeriesFromNumberToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dies ändert die Serie von ähnelt.
        /// </summary>
        public static string ChangesSeriesNextNumber {
            get {
                return ResourceManager.GetString("ChangesSeriesNextNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sender ähnelt.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherheitsabfrage ähnelt.
        /// </summary>
        public static string CheckDialogHeader {
            get {
                return ResourceManager.GetString("CheckDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DVBViewer auswählen ähnelt.
        /// </summary>
        public static string ChooseDVBViewer {
            get {
                return ResourceManager.GetString("ChooseDVBViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Klicken zum Erweitern ähnelt.
        /// </summary>
        public static string ClickExpand {
            get {
                return ResourceManager.GetString("ClickExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die verbunden mit ähnelt.
        /// </summary>
        public static string ConnectedWith {
            get {
                return ResourceManager.GetString("ConnectedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die konnte nicht gelöscht werden ähnelt.
        /// </summary>
        public static string CouldNotDelete {
            get {
                return ResourceManager.GetString("CouldNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen von Aufnahmen ähnelt.
        /// </summary>
        public static string DeleteDialogHeader {
            get {
                return ResourceManager.GetString("DeleteDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du diese Aufnahmen löschen? ähnelt.
        /// </summary>
        public static string DeleteRecordingsQuestion {
            get {
                return ResourceManager.GetString("DeleteRecordingsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In der Beschreibung suchen ähnelt.
        /// </summary>
        public static string DescSearch {
            get {
                return ResourceManager.GetString("DescSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dauer ähnelt.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DVBViewer Clienten ähnelt.
        /// </summary>
        public static string DVBClients {
            get {
                return ResourceManager.GetString("DVBClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Mode ähnelt.
        /// </summary>
        public static string EditMode {
            get {
                return ResourceManager.GetString("EditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktiviert den Edit Mode zum Bearbeiten der Aufnahmen. Zusätzlich werden die Details beim Anklicken einer Zeile deaktiviert. Es können dann auch mehrere Aufnahmen gleichzeit markiert werden. ähnelt.
        /// </summary>
        public static string EditModeToolTip {
            get {
                return ResourceManager.GetString("EditModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Ändern der Serie ähnelt.
        /// </summary>
        public static string ErrorUpdateSeries {
            get {
                return ResourceManager.GetString("ErrorUpdateSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateininfo ähnelt.
        /// </summary>
        public static string FileInfo {
            get {
                return ResourceManager.GetString("FileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateiname ähnelt.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Filter selektiert nicht zusätzlich ähnelt.
        /// </summary>
        public static string FilterAdditionalToolTip {
            get {
                return ResourceManager.GetString("FilterAdditionalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hostname ähnelt.
        /// </summary>
        public static string Hostname {
            get {
                return ResourceManager.GetString("Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info Datei ähnelt.
        /// </summary>
        public static string InfoFile {
            get {
                return ResourceManager.GetString("InfoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lokaler Videoplayer ähnelt.
        /// </summary>
        public static string LocalPlayer {
            get {
                return ResourceManager.GetString("LocalPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Rückgabewert des Servers war: ähnelt.
        /// </summary>
        public static string MessageFromServer {
            get {
                return ResourceManager.GetString("MessageFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zur Serie verschieben ähnelt.
        /// </summary>
        public static string MoveToSeries {
            get {
                return ResourceManager.GetString("MoveToSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl der Aufnahmen ähnelt.
        /// </summary>
        public static string NumberRecordings {
            get {
                return ResourceManager.GetString("NumberRecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl Videos ähnelt.
        /// </summary>
        public static string NumberVideos {
            get {
                return ResourceManager.GetString("NumberVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ähnelt.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pfad ähnelt.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Pfad suchen ähnelt.
        /// </summary>
        public static string PathSearch {
            get {
                return ResourceManager.GetString("PathSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bild ähnelt.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play ähnelt.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wiedergabe ähnelt.
        /// </summary>
        public static string Playback {
            get {
                return ResourceManager.GetString("Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wiedergabe andere Optionen ähnelt.
        /// </summary>
        public static string PlayBackOtherOptions {
            get {
                return ResourceManager.GetString("PlayBackOtherOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play (komplette Liste) ähnelt.
        /// </summary>
        public static string PlayCompleteList {
            get {
                return ResourceManager.GetString("PlayCompleteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im DVBViewer abspielen ähnelt.
        /// </summary>
        public static string PlayInDVBViewer {
            get {
                return ResourceManager.GetString("PlayInDVBViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port ähnelt.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufnahme(n) ähnelt.
        /// </summary>
        public static string Recording_s {
            get {
                return ResourceManager.GetString("Recording_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufnahmedatum ähnelt.
        /// </summary>
        public static string Recordingdate {
            get {
                return ResourceManager.GetString("Recordingdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufnahme bearbeiten ähnelt.
        /// </summary>
        public static string RecordingEditTitle {
            get {
                return ResourceManager.GetString("RecordingEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufnahmen ähnelt.
        /// </summary>
        public static string Recordings {
            get {
                return ResourceManager.GetString("Recordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern und Testen ähnelt.
        /// </summary>
        public static string SaveAndTest {
            get {
                return ResourceManager.GetString("SaveAndTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche ähnelt.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serie ähnelt.
        /// </summary>
        public static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Server gab zurück, dass diese Aufnahme gerade verwendet wird. ähnelt.
        /// </summary>
        public static string ServerLocksTheRecording {
            get {
                return ResourceManager.GetString("ServerLocksTheRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serverstatus ähnelt.
        /// </summary>
        public static string Serverstatus {
            get {
                return ResourceManager.GetString("Serverstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serveraufgaben ähnelt.
        /// </summary>
        public static string Servertasks {
            get {
                return ResourceManager.GetString("Servertasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hostname, Port, Benutzer und Passwort muss ausgefüllt werden. ähnelt.
        /// </summary>
        public static string SettingsPWUSER {
            get {
                return ResourceManager.GetString("SettingsPWUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen für den DVBViewer Media Server vornehmen ähnelt.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Größe ähnelt.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Untertitel (Info) ähnelt.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dies löscht ähnelt.
        /// </summary>
        public static string ThisDeletes {
            get {
                return ResourceManager.GetString("ThisDeletes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titel ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Titel suchen ähnelt.
        /// </summary>
        public static string TitleSearch {
            get {
                return ResourceManager.GetString("TitleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisieren ähnelt.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderung fehlgeschlagen, der Server antwortete mit der Meldung: ähnelt.
        /// </summary>
        public static string UpdateFailedWithCode {
            get {
                return ResourceManager.GetString("UpdateFailedWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Änderung war erfolgreich ähnelt.
        /// </summary>
        public static string UpdateSucceed {
            get {
                return ResourceManager.GetString("UpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwendeter Speicherplatz: ähnelt.
        /// </summary>
        public static string UsedSpace {
            get {
                return ResourceManager.GetString("UsedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername ähnelt.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Videos ähnelt.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Aufnahmen anzeigen ähnelt.
        /// </summary>
        public static string ViewAllRecordings {
            get {
                return ResourceManager.GetString("ViewAllRecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Videos anzeigen ähnelt.
        /// </summary>
        public static string ViewAllVideos {
            get {
                return ResourceManager.GetString("ViewAllVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnung ähnelt.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du diese Änderung durchführen? ähnelt.
        /// </summary>
        public static string YouWantThisUpdate {
            get {
                return ResourceManager.GetString("YouWantThisUpdate", resourceCulture);
            }
        }
    }
}
